# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: e.printStackTrace(); // Blog
#subtitle: Lorem ipsum
description: Blog about programming, created by Upwork's Top Rated freelancer, 10+ years experienced Java/Groovy developer. Contact me if you are looking for an experienced and high quality consultant.
author: Szymon Stepniak
bio: Groovista, Upwork's Top Rated freelancer, Toruń Java User Group founder, open&nbsp;source contributor, Stack Overflow addict, bedroom guitar player. I walk through e.printStackTrace() so you don't have to.
photo: https://www.gravatar.com/avatar/b22c1842c6e8f7f2b9b3ed8c0d4efb4d?s=200
language: en
timezone: Europe/Warsaw

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://e.printstacktrace.blog
root: /
#permalink: :year/:month/:day/:title/
permalink: :title/
permalink_defaults:

pretty_urls:
  trailing_index: false

rss: http://feeds.feedburner.com/Eprintstacktracenet

# Directory
source_dir: source
public_dir: public
tag_dir: t
archive_dir: archives
category_dir: ''
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - ".circleci/*"
include:
  - ".circleci/config.yml"

# Writing
new_post_name: :year/:month/:title.adoc # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: clean-blog
theme: mytheme

disqus_shortname: eprintstacktrace

marked:
  breaks: false

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:wololock/wololock.github.io.git
  branch: master
  ignore_hidden: false

all_minifier: true

# Update versions after updating resources to prevent reading from cache
version:
  css: 50
  js: 5

archive_generator:
  per_page: 0
  yearly: false
  monthly: false
  daily: false

# More detailed settings
popularPosts:
  # (optional) Cache options (Improve generation speed.)
  cache:
    path: cache/hexo-popular-related-posts-ga-cached.json

category:
  header:
    'Micronaut Cookbook': /img/micronaut-bg.jpg
    'How to': /img/index-header2.jpg
    'Programming tips': /images/java-type-inference-bg.jpg
    'Ratpack Cookbook': /images/ratpack-cookbook-bg.jpg
    'Tales from debugger': /img/post-debugger.jpg
    'Jenkins Pipeline Cookbook': /images/jenkins-bg2.jpg
    'jq cookbook': /images/jq-bg.jpg

video:
  id: EIhLl9ebeiA
  size: mqdefault
  title: "Parsing JSON in command-line with jq: sort_by, group_by, limit (part 1) | #jq #json"

stackoverflow:
  profile: https://stackoverflow.com/users/2194470/szymon-stepniak?tab=profile
  reputation: 27,343
  gold: 9
  silver: 61
  bronze: 94

alias:
  youtube/:
    title: Subscribe to my YouTube channel! A new video published every week!
    description: e.printstacktrace.blog YouTube channel is all about programming and learning. Watch a new video every week!
    image: /images/og/youtube.jpg
    url: https://www.youtube.com/c/eprintstacktrace
  buy-me-a-coffee/:
    title: Support my work and buy me a coffee!
    url: https://www.buymeacoffee.com/wololock
  codementor/:
    title: Codementor
    url: https://www.codementor.io/@szymonstpniak

share_post:
  twitter:
    handle: wololock

lazyload:
  enable: true
  imgContainer: true
  post:
    only: true
    excludeEncrypt: true

convertkit:
  domain: tremendous-motivator-1432.ck.page