# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: e.printstacktrace.blog - I help you become a better software developer.
description: Blog about programming, created by Upwork's Top Rated freelancer, 10+ years experienced Java/Groovy developer. Contact me if you are looking for an experienced and high quality consultant.
author: Szymon Stepniak
bio: I help you become a better software developer.
photo: https://www.gravatar.com/avatar/b22c1842c6e8f7f2b9b3ed8c0d4efb4d?s=200
language: en
timezone: Europe/Warsaw

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://e.printstacktrace.blog
root: /
#permalink: :year/:month/:day/:title/
permalink: :title/
permalink_defaults:

pretty_urls:
  trailing_index: false

rss: http://feeds.feedburner.com/Eprintstacktracenet

# Directory
source_dir: source
public_dir: public
tag_dir: t
archive_dir: archives
category_dir: ''
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - ".circleci/*"
include:
  - ".circleci/config.yml"

# Writing
new_post_name: :year/:month/:title.adoc # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 0
  order_by: -date

category_generator:
  path: ''
  per_page: 10
  order_by: -date

tag_generator:
  per_page: 0
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
  "Programmer's Bookshelf": 'programmers-bookshelf'
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: clean-blog
theme: minimal

disqus_shortname: eprintstacktrace

marked:
  breaks: false

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:wololock/wololock.github.io.git
  branch: master
  ignore_hidden: false

all_minifier: true

# Update versions after updating resources to prevent reading from cache
version:
  css: 71
  js: 11

archive_generator:
  per_page: 0
  yearly: false
  monthly: false
  daily: false

# More detailed settings
popularPosts:
  # (optional) Cache options (Improve generation speed.)
  cache:
    path: cache/hexo-popular-related-posts-ga-cached.json

category:
  header:
    'Micronaut Cookbook': /img/micronaut-bg.jpg
    'How to': /img/index-header2.jpg
    'Programming tips': /images/java-type-inference-bg.jpg
    'Ratpack Cookbook': /images/ratpack-cookbook-bg.jpg
    'Tales from debugger': /img/post-debugger.jpg
    'Jenkins Pipeline Cookbook': /images/jenkins-bg2.jpg
    'jq cookbook': /images/jq-bg.jpg

social-media:
  - icon: "fa-twitter"
    name: Twitter
    url: https://twitter.com/wololock
    number: 1.14k
    description: Followers
  - icon: "fa-youtube"
    name: YouTube
    url: https://www.youtube.com/eprintstacktrace
    number: 2.13k
    description: Subscribers
  - icon: "fa-github"
    name: Github
    url: https://github.com/wololock
    number: 105
    description: Followers
  - icon: "fa-stack-overflow"
    name: StackOverflow
    url: https://stackoverflow.com/users/2194470/szymon-stepniak
    number: 29.7k
    description: Reputation

alias:
  youtube/:
    title: Subscribe to my YouTube channel! A new video published every week!
    description: e.printstacktrace.blog YouTube channel is all about programming and learning. Watch a new video every week!
    image: /images/og/youtube.jpg
    url: https://www.youtube.com/c/eprintstacktrace
  buy-me-a-coffee/:
    title: Support my work and buy me a coffee!
    url: https://ko-fi.com/eprintstacktrace
  codementor/:
    title: Codementor
    url: https://www.codementor.io/@szymonstpniak
  gear/camera/:
    url: https://amzn.to/3kAY0wI
  gear/lens/:
    url: https://amzn.to/30KHget
  gear/light/:
    url: https://amzn.to/2XSyv01
  gear/microphone/:
    url: https://amzn.to/2XSyKIt
  gear/sd-card/:
    url: https://amzn.to/2DYPTZR
  gear/hdmicap/:
    url: https://amzn.to/3gGsGJQ
  canva/:
    url: https://canva.7eqqol.net/c/2430749/653612/10068
  grammarly/:
    url: https://www.anrdoezrs.net/click-100154593-11275898
  convertkit/:
    url: https://app.convertkit.com/referrals/l/0de2af60-39b9-4c36-a925-687b4c4189e8
  domaincom/:
    url: https://www.tkqlhce.com/click-100154593-13601620
  audible/:
    url: https://amzn.to/2ZdC8ib
  kindleunlimited/:
    url: https://amzn.to/2DJteRx
  nordvpn/:
    url: https://click.linksynergy.com/fs-bin/click?id=uow2LCEuhvQ&offerid=572706.11&type=3&subid=0
  vidiq/:
    url: https://vidiq.com?afmc=4cf
  udemy/:
    url: https://click.linksynergy.com/fs-bin/click?id=uow2LCEuhvQ&offerid=507388.13533&type=3&subid=0
  youtube-secrets-book/:
    url: https://amzn.to/3mPZKlS
  bluehost/:
    url: https://www.bluehost.com/track/szymonstepniak/

share_post:
  twitter:
    handle: wololock

lazyload:
  enable: true
  imgContainer: true
  post:
    only: true
    excludeEncrypt: true

convertkit:
  domain: tremendous-motivator-1432.ck.page
  threshold: -500

google_analytics: UA-42400890-5
